### ISSUE TITLE
local variable ‘students’ referenced before assignment

### ISSUE THREAD

**Issue by NachoMas** [fatuuse/hass-schoolsoft#2]
Hi! i’m getting an error when running the python script:

<Traceback (most recent call last):
File “./schoolsoft.py”, line 332, in
settings = api.fetch_settings()
File “./schoolsoft.py”, line 100, in fetch_settings
return students
UnboundLocalError: local variable ‘students’ referenced before assignment”>

Any idea of what the problem could be?
thanks!

**Comment by NachoMas** [comment]
Adding de trace with debug enabled:

DEBUG:No testkeys
DEBUG:Try get: https://sms.schoolsoft.se/nora/jsp/student/right_parent_pwdadmin.jsp
DEBUG:Starting new HTTPS connection (1): sms.schoolsoft.se:443
DEBUG:https://sms.schoolsoft.se:443 "GET /nora/jsp/student/right_parent_pwdadmin.jsp HTTP/1.1" 302 0
DEBUG:https://sms.schoolsoft.se:443 "GET /nora/html/redirect_login.htm HTTP/1.1" 200 337
DEBUG:Server number: ('',)
DEBUG:Starting new HTTPS connection (1): sms.schoolsoft.se:443
DEBUG:https://sms.schoolsoft.se:443 "POST /nora/jsp/Login.jsp HTTP/1.1" 302 0
DEBUG:Save cookie in memory
DEBUG:Try get: https://sms.schoolsoft.se/nora/jsp/student/right_parent_pwdadmin.jsp
DEBUG:Starting new HTTPS connection (1): sms.schoolsoft.se:443
DEBUG:https://sms.schoolsoft.se:443 "GET /nora/jsp/student/right_parent_pwdadmin.jsp HTTP/1.1" 200 None
DEBUG:SchoolSoft logged in
Traceback (most recent call last):
  File "/home/nacho/Devel/Git_repos/hass-schoolsoft/./schoolsoft.py", line 355, in <module>
    settings = api.fetch_settings()
  File "/home/nacho/Devel/Git_repos/hass-schoolsoft/./schoolsoft.py", line 80, in fetch_settings
    settings.pretify()
TypeError: 'NoneType' object is not callable

**Comment by fatuuse** [comment]
In Schoolsoft webpage -> Min profil. Do you have the RSS links with names like this? Right now i use that part to collect student id and name.
![sketch-1666714706554](https://user-images.githubusercontent.com/26528052/197828951-4550432e-3812-49bb-831b-37a14aee34cd.png)

**Comment by NachoMas** [comment]
No, I don#t have the menu in the same way. It seems the SchoolSoft version depends on the komun? See attached:
![Screenshot](https://user-images.githubusercontent.com/1379016/197855488-0a61a73e-1ee5-4c14-bba3-ede881116076.png)
